name: build-push-gim

on:
  workflow_dispatch:

env:
  IMAGE_NAME: zzci/gim

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build docker tag
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest

          echo "tag-date=$IMAGE_NAME:$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "tag-build=$IMAGE_NAME:$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.tag-date }}
            ${{ env.tag-build }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
